# -*- coding: utf-8 -*-
"""Yf_Weekly_Data_Extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12g4CVRmgy50QtMBAtVl4iBEKqfUJG1UX
"""

!pip install yfinance openpyxl

import yfinance as yf
import pandas as pd

# Download Hindustan Unilever weekly data
hul = yf.download(
    "HINDUNILVR.NS",
    start="2024-07-24",
    end="2026-07-25",      # End date is exclusive, so use the next day
    interval="1wk",
    auto_adjust=False
)

# Save to Excel
hul.to_excel("HUL_Weekly_24Jul2024_24Jul2026.xlsx")

print(hul)
print("Excel file created successfully!")

import yfinance as yf
import pandas as pd

# Download NIFTY 50 weekly data
nifty = yf.download(
    "^NSEI",
    start="2024-07-24",
    end="2026-07-24",
    interval="1wk",
    auto_adjust=False
)

# Keep only required columns
nifty = nifty[['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']]

# Save to Excel
nifty.to_excel("NIFTY50_Weekly_24Jul2024_24Jul2026.xlsx")

print(nifty)

print("\nExcel file created successfully!")

import yfinance as yf
import pandas as pd

# Download Nestle India weekly data
nestle = yf.download(
    "NESTLEIND.NS"
    start="2024-07-24"
    end="2026-07-25"   #End date is exclusive, so
    interval="1wk",
    auto_adjust=False
)

# Save to Excel
nestle.to_excel("Nestle_Weekly_24Jul2024_24Jul2026.xlsx")

print(nestle)
print("Excel file created successfully!")

import yfinance as yf
import pandas as pd

# Download Nestle India weekly data
nestle = yf.download(
    "NESTLEIND.NS",
    start="2024-07-24",
    end="2026-07-25",      # End date is exclusive, so use the next day
    interval="1wk",
    auto_adjust=False
)

# Save to Excel
nestle.to_excel("nestle_Weekly_24Jul2024_24Jul2026.xlsx")

print(nestle)
print("Excel file created successfully!")

import yfinance as yf
import pandas as pd

# Download BRITANNIA.NS weekly data
britannia = yf.download(
    "BRITANNIA.NS",
    start="2024-07-24",
    end="2026-07-25",      # End date is exclusive, so use the next day
    interval="1wk",
    auto_adjust=False
)

# Save to Excel
britannia.to_excel("britannia_Weekly_24Jul2024_24Jul2026.xlsx")

print(britannia)
print("Excel file created successfully!")

import yfinance as yf
import pandas as pd

# Download DABUR.NS weekly data
dabur = yf.download(
    "DABUR.NS",
    start="2024-07-24",
    end="2026-07-25",      # End date is exclusive, so use the next day
    interval="1wk",
    auto_adjust=False
)

# Save to Excel
dabur.to_excel("dabur_Weekly_24Jul2024_24Jul2026.xlsx")

print(dabur)
print("Excel file created successfully!")

import yfinance as yf
import pandas as pd

# Download GODREJCP.NS weekly data
godrej = yf.download(
    "GODREJCP.NS",
    start="2024-07-24",
    end="2026-07-25",      # End date is exclusive, so use the next day
    interval="1wk",
    auto_adjust=False
)

# Save to Excel
godrej.to_excel("godrej_Weekly_24Jul2024_24Jul2026.xlsx")

print(godrej)
print("Excel file created successfully!")

import yfinance as yf
import pandas as pd

# Download NIFTY 50 weekly data
nifty = yf.download(
    "^NSEI",
    start="2024-07-24",
    end="2026-07-25",
    interval="1wk",
    auto_adjust=False
)

# Keep only required columns
nifty = nifty[['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']]

# Save to Excel
nifty.to_excel("NIFTY50_Weekly_24Jul2024_24Jul2026.xlsx")

print(nifty)

print("\nExcel file created successfully!")

